"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";

type Summary = { income: number; expenses: number; savings: number; savings_rate: number };
type CsvPreview = { columns: string[]; rows: Record<string, string>[] };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }

export default function Home() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [token, setToken] = useState<string | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [error, setError] = useState(""); const [isRegistering, setIsRegistering] = useState(false); const [uploadMessage, setUploadMessage] = useState(""); const [preview, setPreview] = useState<CsvPreview | null>(null); const [mapping, setMapping] = useState<Record<string, string>>({}); const [importing, setImporting] = useState(false);
  useEffect(() => { const saved = window.localStorage.getItem("finance_token"); if (saved) { setToken(saved); loadSummary(saved); } }, []);
  async function loadSummary(accessToken: string) { const response = await fetch(`${API}/api/v1/summary`, { headers: { Authorization: `Bearer ${accessToken}` } }); if (response.ok) setSummary(await response.json()); else { window.localStorage.removeItem("finance_token"); setToken(null); } }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const endpoint = isRegistering ? "/api/v1/auth/register" : "/api/v1/auth/login"; const response = await fetch(`${API}${endpoint}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const body = await response.json(); if (!response.ok) { setError(body.detail ?? (isRegistering ? "Could not create account" : "Could not sign in")); return; } window.localStorage.setItem("finance_token", body.access_token); setToken(body.access_token); loadSummary(body.access_token); }
  async function uploadCsv(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !token) return; setUploadMessage("Reading your CSV..."); const form = new FormData(); form.append("file", file); const response = await fetch(`${API}/api/v1/imports/preview`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); const body = await response.json(); if (!response.ok) { setUploadMessage(body.detail ?? "Could not read this CSV."); return; } const cols = body.columns as string[]; const find = (terms: string[]) => cols.find(column => terms.some(term => column.toLowerCase().includes(term))) ?? ""; setPreview({ columns: cols, rows: body.rows }); setMapping({ date: find(["date", "booked"]), description: find(["description", "narration", "payee", "merchant"]), amount: find(["amount"]), debit: find(["debit", "withdrawal", "dr"]), credit: find(["credit", "deposit", "cr"]) }); setUploadMessage(`Read ${body.rows.length} transactions from ${file.name}. Map the columns below, then import.`); event.target.value = ""; }
  async function commitImport() { if (!token || !preview) return; setImporting(true); setUploadMessage("Normalizing transactions..."); const selected = Object.fromEntries(Object.entries(mapping).filter(([, value]) => value).map(([field, column]) => [column, field])); const normalizedResponse = await fetch(`${API}/api/v1/imports/normalize`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ rows: preview.rows, mapping: selected }) }); const normalizedBody = await normalizedResponse.json(); if (!normalizedResponse.ok) { setUploadMessage(normalizedBody.detail ?? "Could not normalize this file."); setImporting(false); return; } const committedResponse = await fetch(`${API}/api/v1/imports/commit?import_id=${encodeURIComponent(`csv-${Date.now()}`)}`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(normalizedBody.transactions) }); const committedBody = await committedResponse.json(); setUploadMessage(committedResponse.ok ? `Imported ${committedBody.transaction_count} transactions successfully.` : (committedBody.detail ?? "Could not save transactions.")); if (committedResponse.ok) { setPreview(null); await loadSummary(token); } setImporting(false); }
  if (!token) return <main className="auth-shell"><div className="auth-card"><p className="eyebrow">PERSONAL FINANCE</p><h1>{isRegistering ? "Create your account." : "Your money, clearly."}</h1><p className="muted">{isRegistering ? "Create an account to keep your transactions private." : "Sign in to see your monthly spending overview."}</p><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input type="password" required minLength={8} value={password} onChange={event => setPassword(event.target.value)} /></label>{error && <p className="error">{error}</p>}<button className="button">{isRegistering ? "Create account" : "Sign in"}</button></form><button className="link-button" onClick={() => { setIsRegistering(!isRegistering); setError(""); }}>{isRegistering ? "Already have an account? Sign in" : "New here? Create an account"}</button></div></main>;
  const cards = [["Income", money(summary?.income ?? 0), "This month"], ["Expenses", money(summary?.expenses ?? 0), "This month"], ["Savings", money(summary?.savings ?? 0), `${summary?.savings_rate ?? 0}% savings rate`]];
  return <main className="shell"><header className="header"><div><p className="eyebrow">PERSONAL FINANCE</p><h1>Your money, clearly.</h1></div><div className="actions"><label className="button" htmlFor="csv-file">Import CSV</label><button className="button" onClick={() => { window.localStorage.removeItem("finance_token"); window.location.reload(); }}>Sign out</button></div></header><input id="csv-file" className="file-input" type="file" accept=".csv,text/csv" onChange={uploadCsv} /><section className="welcome"><p className="eyebrow">MONTHLY OVERVIEW</p><h2>Good morning.</h2><p>Here is your current financial snapshot.</p></section><section className="cards">{cards.map(([label, value, note]) => <article className="card" key={label}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}</section>{preview ? <section className="mapping-panel"><p className="eyebrow">IMPORT SETUP</p><h2>Map your columns</h2><p className="muted">Choose which CSV column contains each field. Date and description are required, plus either amount or debit and credit.</p><div className="mapping-grid">{["date", "description", "amount", "debit", "credit"].map(field => <label key={field}>{field}<select value={mapping[field] ?? ""} onChange={event => setMapping({ ...mapping, [field]: event.target.value })}><option value="">Not provided</option>{preview.columns.map(column => <option key={column} value={column}>{column}</option>)}</select></label>)}</div><button className="button" disabled={importing} onClick={commitImport}>{importing ? "Importing..." : "Normalize and import"}</button>{uploadMessage && <p className="upload-message">{uploadMessage}</p>}<p className="preview-count">Loaded {preview.rows.length} rows for import (first 10 are previewed).</p></section> : <section className="empty"><div className="icon">＋</div><h2>{summary?.income || summary?.expenses ? "Your spending overview" : "No transactions yet"}</h2><p>{summary?.income || summary?.expenses ? "Your imported transactions will appear here with category trends and insights." : "Upload a CSV statement and we’ll organize your income and expenses into a simple monthly view."}</p><label className="button" htmlFor="csv-file">Import CSV</label>{uploadMessage && <p className="upload-message">{uploadMessage}</p>}</section>}</main>;
}
